project:
  type: book
  output-dir: docs
engine: julia 
book:
  title: "Introduction to Julia Machine Learning"
  logo: Black and White Cube Graphic Design Book Cover.png
  subtitle: Using ScikitLearn
  author: "Athul Sudheesh"
  chapters:
    - index.qmd
    - hellojulia.qmd
    - firstmodel.qmd
    - evaluation.qmd
    - generalizability.qmd
    - modeltuning.qmd
  sidebar: 
    border: true
#bibliography: references.bib

format:
  html:
    theme: litera
    fontsize: 12pt
    page-layout: article
    reader-mode: true
  pdf:
    documentclass: book

website: 
  google-analytics: "G-Y5C915Y3DF"
  twitter-card: true
  opengraph: true