website: 
  google-analytics:
    tracking-id: "G-Y5C915Y3DF"
    version: 4
  twitter-card: true
  opengraph: true
project:
  type: book
  output-dir: docs 
execute:
  daemon: 60000
book:
  title: "Introduction to Julia Machine Learning"
  logo: Black and White Cube Graphic Design Book Cover.png
  subtitle: Using ScikitLearn
  author: "Athul Sudheesh"
  chapters:
    - index.qmd
    - hellojulia.qmd
    - firstmodel.qmd
    - evaluation.qmd
    - generalizability.qmd
    - modeltuning.qmd
    - e2e.qmd
  sidebar: 
    border: true
#bibliography: references.bib

format:
  html:
    theme: litera
    fontsize: 12pt
    page-layout: article
    reader-mode: true
    include-in-header:
      - analytics.html

