---
toc: false

---
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y5C915Y3DF"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y5C915Y3DF');
</script>

# Preface {.unnumbered}

*Introduction to Julia Machine Learning with Scikit-Learn* is an open access book aimed at undergraduate students in non-CS majors who are taking their first course in machine learning. The book assumes very little to no prior knowledge of programming. It is designed in such a way that the book helps the students to get to speed developing machine learning models in the shortest time without diluting the fundamental concepts in ML. Although the book provides some introduction on the basics of setting up a project in Julia, it is no definitive guide to either programming or Julia Language.

*Motivations for writing this book:*

1. At the time of writing this book, there exists a plethora of books on the ScikitLearn python library but none on the Julia port of ScikitLearn. While an experienced Julia user or someone who is new to Julia but has used python scikit-learn finds the documentation of ScikitLearn.jl complete and enough, it might be overwhelming for a complete beginner to both Julia and the ScikitLearn ecosystem. This book exists to cater to that audience.

2. Most introductory books I have come across try to include as many machine learning models as they can, and in the end, they become a survey of the models and their implementation. While these books still cover the foundational concepts in a beautiful manner, they are often lost in the haystack of model details. In this book, we adopt a concepts-first approach compared to the models-first approach adopted by the vast majority of introductory textbooks on applied machine learning. The goal of this book is not to replace these existing introductory books but rather to complement and act as a prequel to them. 

<u>*Acknowledgement*</u>

I would like to thank my mentor, Dr. Richard M. Golden, for training me rigorously in Statistical Machine Learning and providing me with ample opportunities to fine-tune my statistical teaching skills.